// This file was autogenerated by C:\Users\Jochen\Documents\GitHub\SemToNotes\client\lib\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/canvas/canvas.js', ['xrx.canvas', 'xrx.canvas.Mode', 'xrx.canvas.State'], []);
goog.addDependency('../../../../src/canvas/canvasCanvas.js', ['xrx.canvas.Canvas'], ['goog.dom.DomHelper', 'goog.events', 'goog.events.EventType', 'goog.math.AffineTransform', 'goog.net.ImageLoader', 'xrx', 'xrx.canvas', 'xrx.canvas.GroupBackground', 'xrx.canvas.GroupShape', 'xrx.canvas.GroupShapeCreate', 'xrx.canvas.GroupShapeModify', 'xrx.canvas.Mode', 'xrx.canvas.Shield', 'xrx.canvas.State', 'xrx.graphics.Engine', 'xrx.graphics.Graphics']);
goog.addDependency('../../../../src/canvas/canvasGroup.js', ['xrx.canvas.Group'], ['goog.dom.DomHelper', 'goog.events', 'goog.events.EventType', 'goog.events.MouseWheelHandler', 'goog.events.MouseWheelHandler.EventType', 'xrx.canvas.GroupHandler', 'xrx.canvas.Shield', 'xrx.graphics.Graphics']);
goog.addDependency('../../../../src/canvas/canvasGroupBackground.js', ['xrx.canvas.GroupBackground'], ['goog.dom.DomHelper', 'goog.math', 'goog.math.AffineTransform', 'xrx.canvas.Group', 'xrx.canvas.GroupHandler', 'xrx.canvas.Mode', 'xrx.canvas.Shield', 'xrx.canvas.State']);
goog.addDependency('../../../../src/canvas/canvasGroupHandler.js', ['xrx.canvas.GroupHandler'], ['goog.math.AffineTransform', 'xrx.canvas.Handler', 'xrx.canvas.Mode', 'xrx.canvas.State']);
goog.addDependency('../../../../src/canvas/canvasGroupShape.js', ['xrx.canvas.GroupShape'], ['goog.dom.DomHelper', 'xrx.canvas.Group', 'xrx.canvas.GroupBackground', 'xrx.canvas.GroupHandler', 'xrx.graphics.Graphics']);
goog.addDependency('../../../../src/canvas/canvasGroupShapeCreate.js', ['xrx.canvas.GroupShapeCreate'], ['goog.dom.DomHelper', 'xrx.canvas.Group', 'xrx.canvas.GroupBackground', 'xrx.canvas.GroupHandler']);
goog.addDependency('../../../../src/canvas/canvasGroupShapeModify.js', ['xrx.canvas.GroupShapeModify'], ['goog.dom.DomHelper', 'xrx.canvas.Group', 'xrx.canvas.GroupBackground', 'xrx.canvas.GroupHandler', 'xrx.graphics.Graphics']);
goog.addDependency('../../../../src/canvas/canvasHandler.js', ['xrx.canvas.Handler'], ['goog.events', 'goog.events.EventType', 'goog.math', 'xrx.canvas.Mode', 'xrx.graphics.Graphics']);
goog.addDependency('../../../../src/canvas/canvasShield.js', ['xrx.canvas.Shield'], ['xrx.graphics.Graphics']);
goog.addDependency('../../../../src/canvas/canvasToolbar.js', ['xrx.canvas.Toolbar', 'xrx.canvas.ToolbarButton', 'xrx.canvas.ToolbarOption'], ['goog.dom.DomHelper', 'goog.dom.classes', 'goog.events', 'goog.events.EventType', 'xrx.canvas', 'xrx.canvas.Handler']);
goog.addDependency('../../../../src/graphics/graphics.js', ['xrx.graphics', 'xrx.graphics.Engine'], []);
goog.addDependency('../../../../src/graphics/graphicsCoordinate.js', ['xrx.graphics.Coordinate'], ['xrx.graphics']);
goog.addDependency('../../../../src/graphics/graphicsGraphics.js', ['xrx.graphics.Graphics'], ['xrx.svg', 'xrx.svg.Canvas', 'xrx.svg.Circle', 'xrx.svg.Element', 'xrx.svg.Group', 'xrx.svg.Image', 'xrx.svg.Polygon', 'xrx.svg.PolygonCreate', 'xrx.svg.PolygonModify', 'xrx.svg.Rect', 'xrx.svg.RectCreate', 'xrx.svg.RectModify', 'xrx.svg.Shape', 'xrx.svg.VertexDragger']);
goog.addDependency('../../../../src/graphics/svg/svg.js', ['xrx.svg', 'xrx.svg.Namespace'], ['goog.dom', 'goog.math.AffineTransform']);
goog.addDependency('../../../../src/graphics/svg/svgCanvas.js', ['xrx.svg.Canvas'], ['xrx.svg.Element']);
goog.addDependency('../../../../src/graphics/svg/svgCircle.js', ['xrx.svg.Circle'], ['xrx.svg.Element']);
goog.addDependency('../../../../src/graphics/svg/svgElement.js', ['xrx.svg.Element'], ['goog.array', 'xrx.canvas.State', 'xrx.svg', 'xrx.svg.Namespace']);
goog.addDependency('../../../../src/graphics/svg/svgGroup.js', ['xrx.svg.Group'], ['xrx.svg.Element']);
goog.addDependency('../../../../src/graphics/svg/svgImage.js', ['xrx.svg.Image'], ['xrx.svg.Element']);
goog.addDependency('../../../../src/graphics/svg/svgPolygon.js', ['xrx.svg.Polygon', 'xrx.svg.PolygonCreate', 'xrx.svg.PolygonModify'], ['goog.dom', 'goog.dom.classes', 'xrx.graphics.Coordinate', 'xrx.svg.Circle', 'xrx.svg.Element', 'xrx.svg.Group', 'xrx.svg.Shape', 'xrx.svg.VertexDragger']);
goog.addDependency('../../../../src/graphics/svg/svgRect.js', ['xrx.svg.Rect', 'xrx.svg.RectCreate', 'xrx.svg.RectModify'], ['xrx.svg.Element', 'xrx.svg.Polygon', 'xrx.svg.Shape', 'xrx.svg.VertexDragger']);
goog.addDependency('../../../../src/graphics/svg/svgShape.js', ['xrx.svg.Shape'], ['goog.dom.classes', 'xrx.canvas.Mode', 'xrx.canvas.State', 'xrx.svg.Element']);
goog.addDependency('../../../../src/graphics/svg/svgVertexDragger.js', ['xrx.svg.VertexDragger'], ['xrx.canvas.State', 'xrx.svg.Circle', 'xrx.svg.Element']);
goog.addDependency('../../../../src/stn.js', ['xrx.stn'], ['goog.dom.DomHelper', 'xrx', 'xrx.canvas.Canvas', 'xrx.canvas.Toolbar']);
goog.addDependency('../../../../src/xrx.js', ['xrx'], []);
