<<<<<<< HEAD
// This file was autogenerated by ../lib/closure-library/closure/bin/build/depswriter.py.
=======
// This file was autogenerated by C:\Users\Jochen\Documents\GitHub\HKIKoeln\SemToNotes\client\lib\closure-library\closure\bin\build\depswriter.py.
>>>>>>> ed11b0087dee2402832dff8d5fdea3b3bd3b2102
// Please do not edit.
goog.addDependency('../../../../src/SemToNotes.js', ['SemToNotes'], ['goog.dom.DomHelper', 'xrx.drawing.Drawing', 'xrx.drawing.Mode', 'xrx.drawing.Toolbar', 'xrx.engine.Engine', 'xrx.shape.Shape']);
goog.addDependency('../../../../src/drawing/drawing.js', ['xrx.drawing', 'xrx.drawing.Mode', 'xrx.drawing.State'], ['xrx']);
<<<<<<< HEAD
goog.addDependency('../../../../src/drawing/drawingDrawing.js', ['xrx.drawing.Drawing'], ['goog.dom.DomHelper', 'goog.dom.ViewportSizeMonitor', 'goog.events', 'goog.events.EventType', 'goog.net.ImageLoader', 'goog.style', 'xrx', 'xrx.canvas', 'xrx.drawing', 'xrx.drawing.EventTarget', 'xrx.drawing.LayerBackground', 'xrx.drawing.LayerShape', 'xrx.drawing.LayerShapeCreate', 'xrx.drawing.LayerShapeModify', 'xrx.drawing.Mode', 'xrx.drawing.Modifiable', 'xrx.drawing.State', 'xrx.drawing.Viewbox', 'xrx.engine.Engine', 'xrx.engine.Engines', 'xrx.shape', 'xrx.shape.Shape', 'xrx.shape.Shapes', 'xrx.svg', 'xrx.svg.Canvas', 'xrx.vml']);
goog.addDependency('../../../../src/drawing/drawingEventTarget.js', ['xrx.drawing.Event', 'xrx.drawing.EventTarget', 'xrx.drawing.EventType'], ['goog.Disposable', 'goog.events', 'goog.events.EventHandler', 'goog.events.EventType', 'goog.events.MouseWheelHandler', 'goog.events.MouseWheelHandler.EventType', 'goog.math', 'goog.userAgent', 'xrx.drawing.Mode', 'xrx.shape.Shapes']);
goog.addDependency('../../../../src/drawing/drawingLayer.js', ['xrx.drawing.Layer'], ['goog.dom.DomHelper', 'goog.events', 'goog.events.EventType', 'goog.events.MouseWheelHandler', 'goog.events.MouseWheelHandler.EventType', 'xrx.engine.Engines']);
goog.addDependency('../../../../src/drawing/drawingLayerBackground.js', ['xrx.drawing.LayerBackground'], ['goog.dom.DomHelper', 'goog.math', 'goog.math.AffineTransform', 'xrx.drawing.Layer', 'xrx.drawing.Mode', 'xrx.drawing.State', 'xrx.engine.Engine', 'xrx.engine.Engines']);
goog.addDependency('../../../../src/drawing/drawingLayerShape.js', ['xrx.drawing.LayerShape'], ['goog.dom.DomHelper', 'xrx.drawing.Layer', 'xrx.drawing.LayerBackground', 'xrx.engine.Engine', 'xrx.engine.Engines', 'xrx.shape.Polygon', 'xrx.shape.Rect']);
goog.addDependency('../../../../src/drawing/drawingLayerShapeCreate.js', ['xrx.drawing.LayerShapeCreate'], ['goog.dom.DomHelper', 'xrx.drawing.Layer', 'xrx.drawing.LayerBackground', 'xrx.engine.Engine', 'xrx.engine.Engines']);
goog.addDependency('../../../../src/drawing/drawingLayerShapeModify.js', ['xrx.drawing.LayerShapeModify'], ['goog.dom.DomHelper', 'xrx.drawing.Layer', 'xrx.drawing.LayerBackground', 'xrx.engine.Engine', 'xrx.engine.Engines', 'xrx.shape.VertexDragger']);
=======
goog.addDependency('../../../../src/drawing/drawingDrawing.js', ['xrx.drawing.Drawing'], ['goog.dom.DomHelper', 'goog.dom.ViewportSizeMonitor', 'goog.events', 'goog.events.EventType', 'goog.net.ImageLoader', 'goog.style', 'xrx', 'xrx.drawing', 'xrx.drawing.EventTarget', 'xrx.drawing.LayerBackground', 'xrx.drawing.LayerShape', 'xrx.drawing.LayerShapeCreate', 'xrx.drawing.LayerShapeModify', 'xrx.drawing.LayerTool', 'xrx.drawing.Mode', 'xrx.drawing.Modifiable', 'xrx.drawing.State', 'xrx.drawing.Viewbox', 'xrx.graphics.Engine', 'xrx.graphics.Graphics', 'xrx.shape', 'xrx.shape.Shape', 'xrx.shape.Shapes', 'xrx.svg.Canvas']);
goog.addDependency('../../../../src/drawing/drawingEventTarget.js', ['xrx.drawing.Event', 'xrx.drawing.EventTarget', 'xrx.drawing.EventType'], ['goog.Disposable', 'goog.events', 'goog.events.EventHandler', 'goog.events.EventType', 'goog.events.MouseWheelHandler', 'goog.events.MouseWheelHandler.EventType', 'goog.math', 'goog.userAgent', 'xrx.drawing.Mode', 'xrx.shape.Shapes']);
goog.addDependency('../../../../src/drawing/drawingLayer.js', ['xrx.drawing.Layer'], ['goog.dom.DomHelper', 'goog.events', 'goog.events.EventType', 'goog.events.MouseWheelHandler', 'goog.events.MouseWheelHandler.EventType', 'xrx.graphics.Graphics']);
goog.addDependency('../../../../src/drawing/drawingLayerBackground.js', ['xrx.drawing.LayerBackground'], ['goog.dom.DomHelper', 'goog.math', 'goog.math.AffineTransform', 'xrx.drawing.Layer', 'xrx.drawing.Mode', 'xrx.drawing.State', 'xrx.graphics.Engine', 'xrx.graphics.Graphics']);
goog.addDependency('../../../../src/drawing/drawingLayerShape.js', ['xrx.drawing.LayerShape'], ['goog.dom.DomHelper', 'xrx.drawing.Layer', 'xrx.drawing.LayerBackground', 'xrx.graphics.Engine', 'xrx.graphics.Graphics', 'xrx.shape.Polygon', 'xrx.shape.Rect']);
goog.addDependency('../../../../src/drawing/drawingLayerShapeCreate.js', ['xrx.drawing.LayerShapeCreate'], ['goog.dom.DomHelper', 'xrx.drawing.Layer', 'xrx.drawing.LayerBackground', 'xrx.graphics.Engine', 'xrx.graphics.Graphics']);
goog.addDependency('../../../../src/drawing/drawingLayerShapeModify.js', ['xrx.drawing.LayerShapeModify'], ['goog.dom.DomHelper', 'xrx.drawing.Layer', 'xrx.drawing.LayerBackground', 'xrx.graphics.Engine', 'xrx.graphics.Graphics', 'xrx.shape.VertexDragger']);
goog.addDependency('../../../../src/drawing/drawingLayerTool.js', ['xrx.drawing.LayerTool'], ['xrx.drawing.Layer', 'xrx.drawing.tool.Magnifier']);
>>>>>>> ed11b0087dee2402832dff8d5fdea3b3bd3b2102
goog.addDependency('../../../../src/drawing/drawingModifiable.js', ['xrx.drawing.Modifiable'], ['xrx.drawing', 'xrx.shape.VertexDragger']);
goog.addDependency('../../../../src/drawing/drawingToolMagnifier.js', ['xrx.drawing.tool.Magnifier'], ['goog.dom.DomHelper', 'goog.events', 'goog.events.EventType', 'goog.fx.Dragger', 'goog.math.AffineTransform', 'goog.math.Rect', 'goog.style', 'xrx.drawing.tool.Tool', 'xrx.graphics.Engine', 'xrx.graphics.Graphics', 'xrx.svg', 'xrx.vml']);
goog.addDependency('../../../../src/drawing/drawingToolTool.js', ['xrx.drawing.tool.Tool'], []);
goog.addDependency('../../../../src/drawing/drawingToolbar.js', ['xrx.drawing.Toolbar', 'xrx.drawing.ToolbarButton', 'xrx.drawing.ToolbarOption'], ['goog.dom.DomHelper', 'goog.dom.classes', 'goog.events', 'goog.events.EventType', 'xrx.drawing', 'xrx.drawing.EventTarget']);
goog.addDependency('../../../../src/drawing/drawingViewbox.js', ['xrx.drawing.Viewbox'], ['goog.math', 'goog.math.AffineTransform', 'xrx.drawing', 'xrx.engine.Engine']);
goog.addDependency('../../../../src/drawing/shape/shape.js', ['xrx.shape'], ['xrx']);
goog.addDependency('../../../../src/drawing/shape/shapePolygon.js', ['xrx.shape.Polygon', 'xrx.shape.PolygonCreate', 'xrx.shape.PolygonModify'], ['goog.dom', 'goog.dom.classes', 'xrx.engine.Coordinate', 'xrx.engine.Engines', 'xrx.shape.Shape', 'xrx.shape.VertexDragger']);
goog.addDependency('../../../../src/drawing/shape/shapeRect.js', ['xrx.shape.Rect', 'xrx.shape.RectCreate', 'xrx.shape.RectModify'], ['xrx.engine.Engines', 'xrx.shape.Polygon', 'xrx.shape.Shape', 'xrx.shape.VertexDragger']);
goog.addDependency('../../../../src/drawing/shape/shapeShape.js', ['xrx.shape.Shape'], ['xrx.drawing.Mode', 'xrx.drawing.State', 'xrx.engine.Engines', 'xrx.shape']);
goog.addDependency('../../../../src/drawing/shape/shapeShapes.js', ['xrx.shape.Shapes'], ['xrx.shape.Polygon', 'xrx.shape.PolygonCreate', 'xrx.shape.PolygonModify', 'xrx.shape.Rect', 'xrx.shape.RectCreate', 'xrx.shape.RectModify']);
goog.addDependency('../../../../src/drawing/shape/shapeVertexDragger.js', ['xrx.shape.VertexDragger'], ['xrx.drawing.State', 'xrx.engine.Engines', 'xrx.shape.Shape']);
goog.addDependency('../../../../src/engine/canvas/canvas.js', ['xrx.canvas'], ['xrx']);
goog.addDependency('../../../../src/engine/canvas/canvasCanvas.js', ['xrx.canvas.Canvas'], ['goog.dom.DomHelper', 'xrx.canvas.Element']);
goog.addDependency('../../../../src/engine/canvas/canvasCircle.js', ['xrx.canvas.Circle'], ['xrx.canvas.Stylable', 'xrx.graphic.Circle']);
goog.addDependency('../../../../src/engine/canvas/canvasElement.js', ['xrx.canvas.Element'], ['goog.math.AffineTransform', 'xrx.canvas']);
goog.addDependency('../../../../src/engine/canvas/canvasGroup.js', ['xrx.canvas.Group'], ['xrx.canvas.Element']);
goog.addDependency('../../../../src/engine/canvas/canvasImage.js', ['xrx.canvas.Image'], ['goog.math.Box', 'xrx.canvas.Element']);
goog.addDependency('../../../../src/engine/canvas/canvasPolygon.js', ['xrx.canvas.Polygon'], ['xrx.canvas.Stylable', 'xrx.graphic.Polygon']);
goog.addDependency('../../../../src/engine/canvas/canvasRect.js', ['xrx.canvas.Rect'], ['xrx.canvas.Stylable', 'xrx.graphic.Rect']);
goog.addDependency('../../../../src/engine/canvas/canvasStylable.js', ['xrx.canvas.Stylable'], ['xrx.canvas.Element']);
<<<<<<< HEAD
goog.addDependency('../../../../src/engine/engine.js', ['xrx.engine', 'xrx.engine.Engine'], []);
goog.addDependency('../../../../src/engine/engineCoordinate.js', ['xrx.engine.Coordinate'], ['xrx.engine']);
goog.addDependency('../../../../src/engine/engineEngines.js', ['xrx.engine.Engines'], ['xrx.canvas', 'xrx.canvas.Canvas', 'xrx.canvas.Circle', 'xrx.canvas.Element', 'xrx.canvas.Group', 'xrx.canvas.Image', 'xrx.canvas.Polygon', 'xrx.canvas.Rect', 'xrx.svg', 'xrx.svg.Canvas', 'xrx.svg.Circle', 'xrx.svg.Element', 'xrx.svg.Group', 'xrx.svg.Image', 'xrx.svg.Polygon', 'xrx.svg.Rect', 'xrx.vml', 'xrx.vml.Canvas', 'xrx.vml.Circle', 'xrx.vml.Element', 'xrx.vml.Group', 'xrx.vml.Image', 'xrx.vml.Polygon', 'xrx.vml.Rect']);
=======
goog.addDependency('../../../../src/engine/graphics.js', ['xrx.graphics', 'xrx.graphics.Engine'], []);
goog.addDependency('../../../../src/engine/graphicsCoordinate.js', ['xrx.graphics.Coordinate'], ['xrx.graphics']);
goog.addDependency('../../../../src/engine/graphicsGraphics.js', ['xrx.graphics.Graphics'], ['xrx.canvas', 'xrx.canvas.Canvas', 'xrx.canvas.Circle', 'xrx.canvas.Element', 'xrx.canvas.Group', 'xrx.canvas.Image', 'xrx.canvas.Polygon', 'xrx.canvas.Rect', 'xrx.graphics', 'xrx.svg', 'xrx.svg.Canvas', 'xrx.svg.Circle', 'xrx.svg.Element', 'xrx.svg.Group', 'xrx.svg.Image', 'xrx.svg.Polygon', 'xrx.svg.Rect', 'xrx.vml', 'xrx.vml.Canvas', 'xrx.vml.Circle', 'xrx.vml.Element', 'xrx.vml.Group', 'xrx.vml.Image', 'xrx.vml.Polygon', 'xrx.vml.Rect']);
>>>>>>> ed11b0087dee2402832dff8d5fdea3b3bd3b2102
goog.addDependency('../../../../src/engine/svg/svg.js', ['xrx.svg'], ['goog.dom', 'goog.math.AffineTransform', 'xrx']);
goog.addDependency('../../../../src/engine/svg/svgCanvas.js', ['xrx.svg.Canvas'], ['goog.dom.DomHelper', 'xrx.svg.Element']);
goog.addDependency('../../../../src/engine/svg/svgCircle.js', ['xrx.svg.Circle'], ['xrx.graphic.Circle', 'xrx.svg.Element', 'xrx.svg.Stylable']);
goog.addDependency('../../../../src/engine/svg/svgElement.js', ['xrx.svg.Element'], ['goog.array', 'goog.math.AffineTransform', 'goog.style', 'xrx.drawing.State', 'xrx.svg']);
goog.addDependency('../../../../src/engine/svg/svgGroup.js', ['xrx.svg.Group'], ['goog.dom.DomHelper', 'xrx.svg.Element']);
goog.addDependency('../../../../src/engine/svg/svgImage.js', ['xrx.svg.Image'], ['xrx.svg', 'xrx.svg.Element']);
goog.addDependency('../../../../src/engine/svg/svgPolygon.js', ['xrx.svg.Polygon'], ['xrx.graphic.Polygon', 'xrx.svg', 'xrx.svg.Element', 'xrx.svg.Stylable']);
goog.addDependency('../../../../src/engine/svg/svgRect.js', ['xrx.svg.Rect'], ['xrx.graphic.Rect', 'xrx.svg.Element', 'xrx.svg.Stylable']);
goog.addDependency('../../../../src/engine/svg/svgStylable.js', ['xrx.svg.Stylable'], ['xrx.svg.Element']);
goog.addDependency('../../../../src/engine/vml/vml.js', ['xrx.vml'], ['xrx']);
goog.addDependency('../../../../src/engine/vml/vmlCanvas.js', ['xrx.vml.Canvas'], ['goog.dom.DomHelper', 'xrx.vml', 'xrx.vml.Element']);
goog.addDependency('../../../../src/engine/vml/vmlCircle.js', ['xrx.vml.Circle'], ['xrx.graphic.Circle', 'xrx.vml', 'xrx.vml.Element', 'xrx.vml.Stylable']);
goog.addDependency('../../../../src/engine/vml/vmlElement.js', ['xrx.vml.Element'], ['goog.math.AffineTransform', 'goog.style', 'xrx.vml']);
goog.addDependency('../../../../src/engine/vml/vmlGroup.js', ['xrx.vml.Group'], ['xrx.vml.Element']);
goog.addDependency('../../../../src/engine/vml/vmlImage.js', ['xrx.vml.Image'], ['xrx.graphic.Rect', 'xrx.vml', 'xrx.vml.Element']);
goog.addDependency('../../../../src/engine/vml/vmlPolygon.js', ['xrx.vml.Polygon'], ['xrx.graphic.Polygon', 'xrx.vml', 'xrx.vml.Element', 'xrx.vml.Stylable']);
goog.addDependency('../../../../src/engine/vml/vmlRect.js', ['xrx.vml.Rect'], ['xrx.graphic.Rect', 'xrx.vml.Element', 'xrx.vml.Stylable']);
goog.addDependency('../../../../src/engine/vml/vmlStylable.js', ['xrx.vml.Stylable'], ['xrx.vml', 'xrx.vml.Element']);
goog.addDependency('../../../../src/graphic/graphicCircle.js', ['xrx.graphic.Circle'], []);
goog.addDependency('../../../../src/graphic/graphicPolygon.js', ['xrx.graphic.Polygon'], []);
goog.addDependency('../../../../src/graphic/graphicRect.js', ['xrx.graphic.Rect'], []);
goog.addDependency('../../../../src/xrx.js', ['xrx'], []);
