// Copyright 2008 The Closure Library Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

***REMOVED***
***REMOVED*** @fileoverview Protocol Buffer Message base class.
***REMOVED***

goog.provide('goog.proto2.Message');

goog.require('goog.proto2.Descriptor');
goog.require('goog.proto2.FieldDescriptor');
goog.require('goog.proto2.Util');
goog.require('goog.string');



***REMOVED***
***REMOVED*** Abstract base class for all Protocol Buffer 2 messages. It will be
***REMOVED*** subclassed in the code generated by the Protocol Compiler. Any other
***REMOVED*** subclasses are prohibited.
***REMOVED***
***REMOVED***
goog.proto2.Message = function() {
 ***REMOVED*****REMOVED***
  ***REMOVED*** Stores the field values in this message. Keyed by the tag of the fields.
  ***REMOVED*** @type {*}
  ***REMOVED*** @private
 ***REMOVED*****REMOVED***
  this.values_ = {***REMOVED***

 ***REMOVED*****REMOVED***
  ***REMOVED*** Stores the field information (i.e. metadata) about this message.
  ***REMOVED*** @type {Object.<number, !goog.proto2.FieldDescriptor>}
  ***REMOVED*** @private
 ***REMOVED*****REMOVED***
  this.fields_ = this.getDescriptor().getFieldsMap();

 ***REMOVED*****REMOVED***
  ***REMOVED*** The lazy deserializer for this message instance, if any.
  ***REMOVED*** @type {goog.proto2.LazyDeserializer}
  ***REMOVED*** @private
 ***REMOVED*****REMOVED***
  this.lazyDeserializer_ = null;

 ***REMOVED*****REMOVED***
  ***REMOVED*** A map of those fields deserialized, from tag number to their deserialized
  ***REMOVED*** value.
  ***REMOVED*** @type {Object}
  ***REMOVED*** @private
 ***REMOVED*****REMOVED***
  this.deserializedFields_ = null;
***REMOVED***


***REMOVED***
***REMOVED*** An enumeration defining the possible field types.
***REMOVED*** Should be a mirror of that defined in descriptor.h.
***REMOVED***
***REMOVED*** TODO(user): Remove this alias.  The code generator generates code that
***REMOVED*** references this enum, so it needs to exist until the code generator is
***REMOVED*** changed.  The enum was moved to from Message to FieldDescriptor to avoid a
***REMOVED*** dependency cycle.
***REMOVED***
***REMOVED*** Use goog.proto2.FieldDescriptor.FieldType instead.
***REMOVED***
***REMOVED*** @enum {number}
***REMOVED***
goog.proto2.Message.FieldType = {
  DOUBLE: 1,
  FLOAT: 2,
  INT64: 3,
  UINT64: 4,
  INT32: 5,
  FIXED64: 6,
  FIXED32: 7,
  BOOL: 8,
  STRING: 9,
  GROUP: 10,
  MESSAGE: 11,
  BYTES: 12,
  UINT32: 13,
  ENUM: 14,
  SFIXED32: 15,
  SFIXED64: 16,
  SINT32: 17,
  SINT64: 18
***REMOVED***


***REMOVED***
***REMOVED*** All instances of goog.proto2.Message should have a static descriptorObj_
***REMOVED*** property. This is a JSON representation of a Descriptor. The real Descriptor
***REMOVED*** will be deserialized lazily in the getDescriptor() method.
***REMOVED***
***REMOVED*** This declaration is just here for documentation purposes.
***REMOVED*** goog.proto2.Message does not have its own descriptor.
***REMOVED***
***REMOVED*** @type {undefined}
***REMOVED*** @private
***REMOVED***
goog.proto2.Message.descriptorObj_;


***REMOVED***
***REMOVED*** All instances of goog.proto2.Message should have a static descriptor_
***REMOVED*** property. The Descriptor will be deserialized lazily in the getDescriptor()
***REMOVED*** method.
***REMOVED***
***REMOVED*** This declaration is just here for documentation purposes.
***REMOVED*** goog.proto2.Message does not have its own descriptor.
***REMOVED***
***REMOVED*** @type {undefined}
***REMOVED*** @private
***REMOVED***
goog.proto2.Message.descriptor_;


***REMOVED***
***REMOVED*** Initializes the message with a lazy deserializer and its associated data.
***REMOVED*** This method should be called by internal methods ONLY.
***REMOVED***
***REMOVED*** @param {goog.proto2.LazyDeserializer} deserializer The lazy deserializer to
***REMOVED***   use to decode the data on the fly.
***REMOVED***
***REMOVED*** @param {*} data The data to decode/deserialize.
***REMOVED***
goog.proto2.Message.prototype.initializeForLazyDeserializer = function(
    deserializer, data) {

  this.lazyDeserializer_ = deserializer;
  this.values_ = data;
  this.deserializedFields_ = {***REMOVED***
***REMOVED***


***REMOVED***
***REMOVED*** Sets the value of an unknown field, by tag.
***REMOVED***
***REMOVED*** @param {number} tag The tag of an unknown field (must be >= 1).
***REMOVED*** @param {*} value The value for that unknown field.
***REMOVED***
goog.proto2.Message.prototype.setUnknown = function(tag, value) {
  goog.proto2.Util.assert(!this.fields_[tag],
                          'Field is not unknown in this message');

  goog.proto2.Util.assert(tag >= 1, 'Tag is not valid');
  goog.proto2.Util.assert(value !== null, 'Value cannot be null');

  this.values_[tag] = value;
  if (this.deserializedFields_) {
    delete this.deserializedFields_[tag];
  }
***REMOVED***


***REMOVED***
***REMOVED*** Iterates over all the unknown fields in the message.
***REMOVED***
***REMOVED*** @param {function(number,***REMOVED***)} callback A callback method
***REMOVED***     which gets invoked for each unknown field.
***REMOVED*** @param {Object=} opt_scope The scope under which to execute the callback.
***REMOVED***     If not given, the current message will be used.
***REMOVED***
goog.proto2.Message.prototype.forEachUnknown = function(callback, opt_scope) {
  var scope = opt_scope || this;
  for (var key in this.values_) {
    var keyNum = Number(key);
    if (!this.fields_[keyNum]) {
      callback.call(scope, keyNum, this.values_[key]);
    }
  }
***REMOVED***


***REMOVED***
***REMOVED*** Returns the descriptor which describes the current message.
***REMOVED***
***REMOVED*** This only works if we assume people never subclass protobufs.
***REMOVED***
***REMOVED*** @return {!goog.proto2.Descriptor} The descriptor.
***REMOVED***
goog.proto2.Message.prototype.getDescriptor = function() {
  // NOTE(nicksantos): These sorts of indirect references to descriptor
  // through this.constructor are fragile. See the comments
  // in set$Metadata for more info.
  var Ctor = this.constructor;
  return Ctor.descriptor_ ||
      (Ctor.descriptor_ = goog.proto2.Message.create$Descriptor(
          Ctor, Ctor.descriptorObj_));
***REMOVED***


***REMOVED***
***REMOVED*** Returns whether there is a value stored at the field specified by the
***REMOVED*** given field descriptor.
***REMOVED***
***REMOVED*** @param {goog.proto2.FieldDescriptor} field The field for which to check
***REMOVED***     if there is a value.
***REMOVED***
***REMOVED*** @return {boolean} True if a value was found.
***REMOVED***
goog.proto2.Message.prototype.has = function(field) {
  goog.proto2.Util.assert(
      field.getContainingType() == this.getDescriptor(),
      'The current message does not contain the given field');

  return this.has$Value(field.getTag());
***REMOVED***


***REMOVED***
***REMOVED*** Returns the array of values found for the given repeated field.
***REMOVED***
***REMOVED*** @param {goog.proto2.FieldDescriptor} field The field for which to
***REMOVED***     return the values.
***REMOVED***
***REMOVED*** @return {!Array} The values found.
***REMOVED***
goog.proto2.Message.prototype.arrayOf = function(field) {
  goog.proto2.Util.assert(
      field.getContainingType() == this.getDescriptor(),
      'The current message does not contain the given field');

  return this.array$Values(field.getTag());
***REMOVED***


***REMOVED***
***REMOVED*** Returns the number of values stored in the given field.
***REMOVED***
***REMOVED*** @param {goog.proto2.FieldDescriptor} field The field for which to count
***REMOVED***     the number of values.
***REMOVED***
***REMOVED*** @return {number} The count of the values in the given field.
***REMOVED***
goog.proto2.Message.prototype.countOf = function(field) {
  goog.proto2.Util.assert(
      field.getContainingType() == this.getDescriptor(),
      'The current message does not contain the given field');

  return this.count$Values(field.getTag());
***REMOVED***


***REMOVED***
***REMOVED*** Returns the value stored at the field specified by the
***REMOVED*** given field descriptor.
***REMOVED***
***REMOVED*** @param {goog.proto2.FieldDescriptor} field The field for which to get the
***REMOVED***     value.
***REMOVED*** @param {number=} opt_index If the field is repeated, the index to use when
***REMOVED***     looking up the value.
***REMOVED***
***REMOVED*** @return {*} The value found or null if none.
***REMOVED***
goog.proto2.Message.prototype.get = function(field, opt_index) {
  goog.proto2.Util.assert(
      field.getContainingType() == this.getDescriptor(),
      'The current message does not contain the given field');

  return this.get$Value(field.getTag(), opt_index);
***REMOVED***


***REMOVED***
***REMOVED*** Returns the value stored at the field specified by the
***REMOVED*** given field descriptor or the default value if none exists.
***REMOVED***
***REMOVED*** @param {goog.proto2.FieldDescriptor} field The field for which to get the
***REMOVED***     value.
***REMOVED*** @param {number=} opt_index If the field is repeated, the index to use when
***REMOVED***     looking up the value.
***REMOVED***
***REMOVED*** @return {*} The value found or the default if none.
***REMOVED***
goog.proto2.Message.prototype.getOrDefault = function(field, opt_index) {
  goog.proto2.Util.assert(
      field.getContainingType() == this.getDescriptor(),
      'The current message does not contain the given field');

  return this.get$ValueOrDefault(field.getTag(), opt_index);
***REMOVED***


***REMOVED***
***REMOVED*** Stores the given value to the field specified by the
***REMOVED*** given field descriptor. Note that the field must not be repeated.
***REMOVED***
***REMOVED*** @param {goog.proto2.FieldDescriptor} field The field for which to set
***REMOVED***     the value.
***REMOVED*** @param {*} value The new value for the field.
***REMOVED***
goog.proto2.Message.prototype.set = function(field, value) {
  goog.proto2.Util.assert(
      field.getContainingType() == this.getDescriptor(),
      'The current message does not contain the given field');

  this.set$Value(field.getTag(), value);
***REMOVED***


***REMOVED***
***REMOVED*** Adds the given value to the field specified by the
***REMOVED*** given field descriptor. Note that the field must be repeated.
***REMOVED***
***REMOVED*** @param {goog.proto2.FieldDescriptor} field The field in which to add the
***REMOVED***     the value.
***REMOVED*** @param {*} value The new value to add to the field.
***REMOVED***
goog.proto2.Message.prototype.add = function(field, value) {
  goog.proto2.Util.assert(
      field.getContainingType() == this.getDescriptor(),
      'The current message does not contain the given field');

  this.add$Value(field.getTag(), value);
***REMOVED***


***REMOVED***
***REMOVED*** Clears the field specified.
***REMOVED***
***REMOVED*** @param {goog.proto2.FieldDescriptor} field The field to clear.
***REMOVED***
goog.proto2.Message.prototype.clear = function(field) {
  goog.proto2.Util.assert(
      field.getContainingType() == this.getDescriptor(),
      'The current message does not contain the given field');

  this.clear$Field(field.getTag());
***REMOVED***


***REMOVED***
***REMOVED*** Compares this message with another one ignoring the unknown fields.
***REMOVED*** @param {*} other The other message.
***REMOVED*** @return {boolean} Whether they are equal. Returns false if the {@code other}
***REMOVED***     argument is a different type of message or not a message.
***REMOVED***
goog.proto2.Message.prototype.equals = function(other) {
  if (!other || this.constructor != other.constructor) {
    return false;
  }

  var fields = this.getDescriptor().getFields();
  for (var i = 0; i < fields.length; i++) {
    var field = fields[i];
    if (this.has(field) != other.has(field)) {
      return false;
    }

    if (this.has(field)) {
      var isComposite = field.isCompositeType();

      var fieldsEqual = function(value1, value2) {
        return isComposite ? value1.equals(value2) : value1 == value2;
     ***REMOVED*****REMOVED***

      var thisValue = this.getValueForField_(field);
      var otherValue = other.getValueForField_(field);

      if (field.isRepeated()) {
        // In this case thisValue and otherValue are arrays.
        if (thisValue.length != otherValue.length) {
          return false;
        }
        for (var j = 0; j < thisValue.length; j++) {
          if (!fieldsEqual(thisValue[j], otherValue[j])) {
            return false;
          }
        }
      } else if (!fieldsEqual(thisValue, otherValue)) {
        return false;
      }
    }
  }

  return true;
***REMOVED***


***REMOVED***
***REMOVED*** Recursively copies the known fields from the given message to this message.
***REMOVED*** Removes the fields which are not present in the source message.
***REMOVED*** @param {!goog.proto2.Message} message The source message.
***REMOVED***
goog.proto2.Message.prototype.copyFrom = function(message) {
  goog.proto2.Util.assert(this.constructor == message.constructor,
      'The source message must have the same type.');

  if (this != message) {
    this.values_ = {***REMOVED***
    if (this.deserializedFields_) {
      this.deserializedFields_ = {***REMOVED***
    }
    this.mergeFrom(message);
  }
***REMOVED***


***REMOVED***
***REMOVED*** Merges the given message into this message.
***REMOVED***
***REMOVED*** Singular fields will be overwritten, except for embedded messages which will
***REMOVED*** be merged. Repeated fields will be concatenated.
***REMOVED*** @param {!goog.proto2.Message} message The source message.
***REMOVED***
goog.proto2.Message.prototype.mergeFrom = function(message) {
  goog.proto2.Util.assert(this.constructor == message.constructor,
      'The source message must have the same type.');
  var fields = this.getDescriptor().getFields();

  for (var i = 0; i < fields.length; i++) {
    var field = fields[i];
    if (message.has(field)) {
      if (this.deserializedFields_) {
        delete this.deserializedFields_[field.getTag()];
      }

      var isComposite = field.isCompositeType();
      if (field.isRepeated()) {
        var values = message.arrayOf(field);
        for (var j = 0; j < values.length; j++) {
          this.add(field, isComposite ? values[j].clone() : values[j]);
        }
      } else {
        var value = message.getValueForField_(field);
        if (isComposite) {
          var child = this.getValueForField_(field);
          if (child) {
            child.mergeFrom(value);
          } else {
            this.set(field, value.clone());
          }
        } else {
          this.set(field, value);
        }
      }
    }
  }
***REMOVED***


***REMOVED***
***REMOVED*** @return {!goog.proto2.Message} Recursive clone of the message only including
***REMOVED***     the known fields.
***REMOVED***
goog.proto2.Message.prototype.clone = function() {
  var clone = new this.constructor;
  clone.copyFrom(this);
  return clone;
***REMOVED***


***REMOVED***
***REMOVED*** Fills in the protocol buffer with default values. Any fields that are
***REMOVED*** already set will not be overridden.
***REMOVED*** @param {boolean} simpleFieldsToo If true, all fields will be initialized;
***REMOVED***     if false, only the nested messages and groups.
***REMOVED***
goog.proto2.Message.prototype.initDefaults = function(simpleFieldsToo) {
  var fields = this.getDescriptor().getFields();
  for (var i = 0; i < fields.length; i++) {
    var field = fields[i];
    var tag = field.getTag();
    var isComposite = field.isCompositeType();

    // Initialize missing fields.
    if (!this.has(field) && !field.isRepeated()) {
      if (isComposite) {
        this.values_[tag] = new***REMOVED*****REMOVED*** @type {Function}***REMOVED*** (field.getNativeType());
      } else if (simpleFieldsToo) {
        this.values_[tag] = field.getDefaultValue();
      }
    }

    // Fill in the existing composite fields recursively.
    if (isComposite) {
      if (field.isRepeated()) {
        var values = this.array$Values(tag);
        for (var j = 0; j < values.length; j++) {
          values[j].initDefaults(simpleFieldsToo);
        }
      } else {
        this.get$Value(tag).initDefaults(simpleFieldsToo);
      }
    }
  }
***REMOVED***


***REMOVED***
***REMOVED*** Returns the field in this message by the given tag number. If no
***REMOVED*** such field exists, throws an exception.
***REMOVED***
***REMOVED*** @param {number} tag The field's tag index.
***REMOVED*** @return {!goog.proto2.FieldDescriptor} The descriptor for the field.
***REMOVED*** @private
***REMOVED***
goog.proto2.Message.prototype.getFieldByTag_ = function(tag) {
  goog.proto2.Util.assert(this.fields_[tag],
                          'No field found for the given tag');

  return this.fields_[tag];
***REMOVED***


***REMOVED***
***REMOVED*** Returns the whether or not the field indicated by the given tag
***REMOVED*** has a value.
***REMOVED***
***REMOVED*** GENERATED CODE USE ONLY. Basis of the has{Field} methods.
***REMOVED***
***REMOVED*** @param {number} tag The tag.
***REMOVED***
***REMOVED*** @return {boolean} Whether the message has a value for the field.
***REMOVED***
goog.proto2.Message.prototype.has$Value = function(tag) {
  goog.proto2.Util.assert(this.fields_[tag],
                          'No field found for the given tag');

  return tag in this.values_ && goog.isDef(this.values_[tag]) &&
      this.values_[tag] !== null;
***REMOVED***


***REMOVED***
***REMOVED*** Returns the value for the given field. If a lazy deserializer is
***REMOVED*** instantiated, lazily deserializes the field if required before returning the
***REMOVED*** value.
***REMOVED***
***REMOVED*** @param {goog.proto2.FieldDescriptor} field The field.
***REMOVED*** @return {*} The field value, if any.
***REMOVED*** @private
***REMOVED***
goog.proto2.Message.prototype.getValueForField_ = function(field) {
  // Retrieve the current value, which may still be serialized.
  var tag = field.getTag();
  if (!tag in this.values_) {
    return null;
  }

  var value = this.values_[tag];
  if (value == null) {
    return null;
  }

  // If we have a lazy deserializer, then ensure that the field is
  // properly deserialized.
  if (this.lazyDeserializer_) {
    // If the tag is not deserialized, then we must do so now. Deserialize
    // the field's value via the deserializer.
    if (!(tag in this.deserializedFields_)) {
      var deserializedValue = this.lazyDeserializer_.deserializeField(
          this, field, value);
      this.deserializedFields_[tag] = deserializedValue;
      return deserializedValue;
    }

    return this.deserializedFields_[tag];
  }

  // Otherwise, just return the value.
  return value;
***REMOVED***


***REMOVED***
***REMOVED*** Gets the value at the field indicated by the given tag.
***REMOVED***
***REMOVED*** GENERATED CODE USE ONLY. Basis of the get{Field} methods.
***REMOVED***
***REMOVED*** @param {number} tag The field's tag index.
***REMOVED*** @param {number=} opt_index If the field is a repeated field, the index
***REMOVED***     at which to get the value.
***REMOVED***
***REMOVED*** @return {*} The value found or null for none.
***REMOVED*** @protected
***REMOVED***
goog.proto2.Message.prototype.get$Value = function(tag, opt_index) {
  var field = this.getFieldByTag_(tag);
  var value = this.getValueForField_(field);

  if (field.isRepeated()) {
    goog.proto2.Util.assert(goog.isArray(value));

    var index = opt_index || 0;
    goog.proto2.Util.assert(index >= 0 && index < value.length,
        'Given index is out of bounds');

    return value[index];
  }

  goog.proto2.Util.assert(!goog.isArray(value));
  return value;
***REMOVED***


***REMOVED***
***REMOVED*** Gets the value at the field indicated by the given tag or the default value
***REMOVED*** if none.
***REMOVED***
***REMOVED*** GENERATED CODE USE ONLY. Basis of the get{Field} methods.
***REMOVED***
***REMOVED*** @param {number} tag The field's tag index.
***REMOVED*** @param {number=} opt_index If the field is a repeated field, the index
***REMOVED***     at which to get the value.
***REMOVED***
***REMOVED*** @return {*} The value found or the default value if none set.
***REMOVED*** @protected
***REMOVED***
goog.proto2.Message.prototype.get$ValueOrDefault = function(tag, opt_index) {

  if (!this.has$Value(tag)) {
    // Return the default value.
    var field = this.getFieldByTag_(tag);
    return field.getDefaultValue();
  }

  return this.get$Value(tag, opt_index);
***REMOVED***


***REMOVED***
***REMOVED*** Gets the values at the field indicated by the given tag.
***REMOVED***
***REMOVED*** GENERATED CODE USE ONLY. Basis of the {field}Array methods.
***REMOVED***
***REMOVED*** @param {number} tag The field's tag index.
***REMOVED***
***REMOVED*** @return {!Array} The values found. If none, returns an empty array.
***REMOVED*** @protected
***REMOVED***
goog.proto2.Message.prototype.array$Values = function(tag) {
  goog.proto2.Util.assert(this.getFieldByTag_(tag).isRepeated(),
      'Cannot call fieldArray on a non-repeated field');
  var field = this.getFieldByTag_(tag);
  var value = this.getValueForField_(field);
  goog.proto2.Util.assert(value == null || goog.isArray(value));
  return***REMOVED*****REMOVED*** @type {Array}***REMOVED*** (value) || [];
***REMOVED***


***REMOVED***
***REMOVED*** Returns the number of values stored in the field by the given tag.
***REMOVED***
***REMOVED*** GENERATED CODE USE ONLY. Basis of the {field}Count methods.
***REMOVED***
***REMOVED*** @param {number} tag The tag.
***REMOVED***
***REMOVED*** @return {number} The number of values.
***REMOVED*** @protected
***REMOVED***
goog.proto2.Message.prototype.count$Values = function(tag) {
  var field = this.getFieldByTag_(tag);

  if (field.isRepeated()) {
    if (this.has$Value(tag)) {
      goog.proto2.Util.assert(goog.isArray(this.values_[tag]));
    }

    return this.has$Value(tag) ? this.values_[tag].length : 0;
  } else {
    return this.has$Value(tag) ? 1 : 0;
  }
***REMOVED***


***REMOVED***
***REMOVED*** Sets the value of the***REMOVED***non-repeating* field indicated by the given tag.
***REMOVED***
***REMOVED*** GENERATED CODE USE ONLY. Basis of the set{Field} methods.
***REMOVED***
***REMOVED*** @param {number} tag The field's tag index.
***REMOVED*** @param {*} value The field's value.
***REMOVED*** @protected
***REMOVED***
goog.proto2.Message.prototype.set$Value = function(tag, value) {
  if (goog.proto2.Util.conductChecks()) {
    var field = this.getFieldByTag_(tag);

    goog.proto2.Util.assert(!field.isRepeated(),
                            'Cannot call set on a repeated field');

    this.checkFieldType_(field, value);
  }

  this.values_[tag] = value;
  if (this.deserializedFields_) {
    this.deserializedFields_[tag] = value;
  }
***REMOVED***


***REMOVED***
***REMOVED*** Adds the value to the***REMOVED***repeating* field indicated by the given tag.
***REMOVED***
***REMOVED*** GENERATED CODE USE ONLY. Basis of the add{Field} methods.
***REMOVED***
***REMOVED*** @param {number} tag The field's tag index.
***REMOVED*** @param {*} value The value to add.
***REMOVED*** @protected
***REMOVED***
goog.proto2.Message.prototype.add$Value = function(tag, value) {
  if (goog.proto2.Util.conductChecks()) {
    var field = this.getFieldByTag_(tag);

    goog.proto2.Util.assert(field.isRepeated(),
                            'Cannot call add on a non-repeated field');

    this.checkFieldType_(field, value);
  }

  if (!this.values_[tag]) {
    this.values_[tag] = [];
  }

  this.values_[tag].push(value);
  if (this.deserializedFields_) {
    delete this.deserializedFields_[tag];
  }
***REMOVED***


***REMOVED***
***REMOVED*** Ensures that the value being assigned to the given field
***REMOVED*** is valid.
***REMOVED***
***REMOVED*** @param {!goog.proto2.FieldDescriptor} field The field being assigned.
***REMOVED*** @param {*} value The value being assigned.
***REMOVED*** @private
***REMOVED***
goog.proto2.Message.prototype.checkFieldType_ = function(field, value) {
  goog.proto2.Util.assert(value !== null);

  var nativeType = field.getNativeType();
  if (nativeType === String) {
    goog.proto2.Util.assert(typeof value === 'string',
                            'Expected value of type string');
  } else if (nativeType === Boolean) {
    goog.proto2.Util.assert(typeof value === 'boolean',
                            'Expected value of type boolean');
  } else if (nativeType === Number) {
    goog.proto2.Util.assert(typeof value === 'number',
                            'Expected value of type number');
  } else if (field.getFieldType() ==
             goog.proto2.FieldDescriptor.FieldType.ENUM) {
    goog.proto2.Util.assert(typeof value === 'number',
                            'Expected an enum value, which is a number');
  } else {
    goog.proto2.Util.assert(value instanceof nativeType,
                            'Expected a matching message type');
  }
***REMOVED***


***REMOVED***
***REMOVED*** Clears the field specified by tag.
***REMOVED***
***REMOVED*** GENERATED CODE USE ONLY. Basis of the clear{Field} methods.
***REMOVED***
***REMOVED*** @param {number} tag The tag of the field to clear.
***REMOVED*** @protected
***REMOVED***
goog.proto2.Message.prototype.clear$Field = function(tag) {
  goog.proto2.Util.assert(this.getFieldByTag_(tag), 'Unknown field');
  delete this.values_[tag];
  if (this.deserializedFields_) {
    delete this.deserializedFields_[tag];
  }
***REMOVED***


***REMOVED***
***REMOVED*** Creates the metadata descriptor representing the definition of this message.
***REMOVED***
***REMOVED*** GENERATED CODE USE ONLY. Called when constructing message classes.
***REMOVED***
***REMOVED*** @param {function(new:goog.proto2.Message)} messageType Constructor for the
***REMOVED***     message type to which this metadata applies.
***REMOVED*** @param {Object} metadataObj The object containing the metadata.
***REMOVED*** @return {!goog.proto2.Descriptor} The new descriptor.
***REMOVED***
goog.proto2.Message.create$Descriptor = function(messageType, metadataObj) {
  var fields = [];
  var descriptorInfo;

  for (var key in metadataObj) {
    if (!metadataObj.hasOwnProperty(key)) {
      continue;
    }

    goog.proto2.Util.assert(goog.string.isNumeric(key), 'Keys must be numeric');

    if (key == 0) {
      descriptorInfo = metadataObj[0];
      continue;
    }

    // Create the field descriptor.
    fields.push(
        new goog.proto2.FieldDescriptor(messageType, key, metadataObj[key]));
  }

  goog.proto2.Util.assert(descriptorInfo);
  return new goog.proto2.Descriptor(messageType, descriptorInfo, fields);
***REMOVED***


***REMOVED***
***REMOVED*** Sets the metadata that represents the definition of this message.
***REMOVED***
***REMOVED*** GENERATED CODE USE ONLY. Called when constructing message classes.
***REMOVED***
***REMOVED*** @param {!Function} messageType Constructor for the
***REMOVED***     message type to which this metadata applies.
***REMOVED*** @param {Object} metadataObj The object containing the metadata.
***REMOVED***
goog.proto2.Message.set$Metadata = function(messageType, metadataObj) {
  // NOTE(nicksantos): JSCompiler's type-based optimizations really do not
  // like indirectly defined methods (both prototype methods and
  // static methods). This is very fragile in compiled code. I think it only
  // really works by accident, and is highly likely to break in the future.
  messageType.descriptorObj_ = metadataObj;
  messageType.getDescriptor = function() {
    // The descriptor is created lazily when we instantiate a new instance.
    return messageType.descriptor_ ||
        (new messageType()).getDescriptor();
 ***REMOVED*****REMOVED***
***REMOVED***
